### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by QiyaoWei** [QiyaoWei/Scrapy---Python#1]
testing

```
/Users/qiyaowei/anaconda3/envs/cur/bin/python /Users/qiyaowei/qcqp/mwe.py
===============================================================================
                                     CVXPY                                     
                                    v1.1.12                                    
===============================================================================
(CVXPY) May 10 04:11:47 PM: Your problem has 80 variables, 20 constraints, and 0 parameters.
(CVXPY) May 10 04:11:47 PM: It is compliant with the following grammars: 
(CVXPY) May 10 04:11:47 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 10 04:11:47 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
Traceback (most recent call last):
  File "/Users/qiyaowei/qcqp/mwe.py", line 56, in <module>
    low_lp = init_lp_relaxation(A, a, b, sign, np.random.randint(0, 10, (n, 1)), solver='MOSEK', sense='min', verbose=True,
  File "/Users/qiyaowei/qcqp/mwe.py", line 31, in init_lp_relaxation
    problem.solve(verbose=verbose, solver=solver)
  File "/Users/qiyaowei/anaconda3/envs/cur/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 459, in solve
    return solve_func(self, *args, **kwargs)
  File "/Users/qiyaowei/anaconda3/envs/cur/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 938, in _solve
    data, solving_chain, inverse_data = self.get_problem_data(
  File "/Users/qiyaowei/anaconda3/envs/cur/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 565, in get_problem_data
    solving_chain = self._construct_chain(
  File "/Users/qiyaowei/anaconda3/envs/cur/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 791, in _construct_chain
    return construct_solving_chain(self, candidate_solvers, gp=gp,
  File "/Users/qiyaowei/anaconda3/envs/cur/lib/python3.8/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 155, in construct_solving_chain
    reductions = _reductions_for_problem_class(problem, candidates, gp)
  File "/Users/qiyaowei/anaconda3/envs/cur/lib/python3.8/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 91, in _reductions_for_problem_class
    raise DCPError(
cvxpy.error.DCPError: Problem does not follow DCP rules. Specifically:
The following constraints are not DCP:
0.5 @ QuadForm(var0, [[2. 1. 1. ... 1. 2. 1.]
 [1. 2. 1. ... 1. 1. 2.]
 [1. 1. 2. ... 0. 2. 1.]
 ...
 [1. 1. 0. ... 2. 1. 1.]
 [2. 1. 2. ... 1. 2. 1.]
 [1. 2. 1. ... 1. 1. 2.]]) + trace([[1. 0. 4. 2. 4. 0. 2. 1. 3. 4. 0. 0. 1. 0. 0. 0. 3. 0. 3. 1. 1. 2. 3. 0.
  2. 3. 0. 1. 1. 3. 2. 4. 4. 0. 1. 3. 3. 2. 4. 2. 1. 0. 2. 1. 3. 3. 0. 3.
  0. 1. 0. 2. 4. 4. 4. 4. 0. 0. 2. 3. 4. 2. 1. 3. 0. 3. 0. 4. 4. 4. 0. 4.
  2. 0. 0. 0. 3. 3. 0. 4.]] @ var0) <= 103.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[2. 1. 1. ... 1. 2. 1.]
 [1. 2. 1. ... 1. 1. 2.]
 [1. 1. 2. ... 0. 2. 1.]
 ...
 [1. 1. 0. ... 2. 1. 1.]
 [2. 1. 2. ... 1. 2. 1.]
 [1. 2. 1. ... 1. 1. 2.]]) + trace([[1. 0. 4. 2. 4. 0. 2. 1. 3. 4. 0. 0. 1. 0. 0. 0. 3. 0. 3. 1. 1. 2. 3. 0.
  2. 3. 0. 1. 1. 3. 2. 4. 4. 0. 1. 3. 3. 2. 4. 2. 1. 0. 2. 1. 3. 3. 0. 3.
  0. 1. 0. 2. 4. 4. 4. 4. 0. 0. 2. 3. 4. 2. 1. 3. 0. 3. 0. 4. 4. 4. 0. 4.
  2. 0. 0. 0. 3. 3. 0. 4.]] @ var0) <= 103.0
0.5 @ QuadForm(var0, [[0. 1. 1. ... 0. 1. 1.]
 [1. 0. 0. ... 1. 2. 0.]
 [1. 0. 2. ... 0. 2. 1.]
 ...
 [0. 1. 0. ... 2. 0. 1.]
 [1. 2. 2. ... 0. 0. 1.]
 [1. 0. 1. ... 1. 1. 0.]]) + trace([[4. 1. 3. 1. 4. 0. 1. 2. 4. 2. 0. 4. 1. 3. 2. 4. 1. 2. 0. 2. 2. 3. 2. 1.
  0. 3. 3. 4. 2. 1. 0. 3. 0. 1. 4. 3. 1. 1. 1. 2. 4. 4. 1. 0. 3. 4. 3. 3.
  4. 4. 4. 4. 2. 0. 3. 0. 4. 3. 0. 0. 3. 3. 2. 3. 1. 4. 4. 0. 2. 0. 2. 3.
  1. 4. 1. 3. 4. 2. 3. 0.]] @ var0) <= 155.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[0. 1. 1. ... 0. 1. 1.]
 [1. 0. 0. ... 1. 2. 0.]
 [1. 0. 2. ... 0. 2. 1.]
 ...
 [0. 1. 0. ... 2. 0. 1.]
 [1. 2. 2. ... 0. 0. 1.]
 [1. 0. 1. ... 1. 1. 0.]]) + trace([[4. 1. 3. 1. 4. 0. 1. 2. 4. 2. 0. 4. 1. 3. 2. 4. 1. 2. 0. 2. 2. 3. 2. 1.
  0. 3. 3. 4. 2. 1. 0. 3. 0. 1. 4. 3. 1. 1. 1. 2. 4. 4. 1. 0. 3. 4. 3. 3.
  4. 4. 4. 4. 2. 0. 3. 0. 4. 3. 0. 0. 3. 3. 2. 3. 1. 4. 4. 0. 2. 0. 2. 3.
  1. 4. 1. 3. 4. 2. 3. 0.]] @ var0) <= 155.0
0.5 @ QuadForm(var0, [[0. 1. 1. ... 2. 1. 1.]
 [1. 2. 1. ... 0. 1. 0.]
 [1. 1. 2. ... 2. 1. 1.]
 ...
 [2. 0. 2. ... 0. 1. 2.]
 [1. 1. 1. ... 1. 2. 1.]
 [1. 0. 1. ... 2. 1. 0.]]) + trace([[0. 2. 1. 3. 2. 2. 1. 0. 1. 0. 4. 0. 1. 3. 4. 0. 3. 3. 1. 1. 1. 0. 4. 0.
  1. 2. 4. 2. 0. 1. 1. 3. 3. 4. 3. 2. 2. 3. 4. 4. 1. 3. 1. 4. 3. 1. 1. 4.
  1. 3. 0. 1. 3. 1. 4. 1. 4. 2. 0. 2. 2. 1. 2. 1. 0. 0. 0. 2. 2. 0. 3. 1.
  2. 2. 4. 4. 3. 4. 0. 2.]] @ var0) <= 204.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[0. 1. 1. ... 2. 1. 1.]
 [1. 2. 1. ... 0. 1. 0.]
 [1. 1. 2. ... 2. 1. 1.]
 ...
 [2. 0. 2. ... 0. 1. 2.]
 [1. 1. 1. ... 1. 2. 1.]
 [1. 0. 1. ... 2. 1. 0.]]) + trace([[0. 2. 1. 3. 2. 2. 1. 0. 1. 0. 4. 0. 1. 3. 4. 0. 3. 3. 1. 1. 1. 0. 4. 0.
  1. 2. 4. 2. 0. 1. 1. 3. 3. 4. 3. 2. 2. 3. 4. 4. 1. 3. 1. 4. 3. 1. 1. 4.
  1. 3. 0. 1. 3. 1. 4. 1. 4. 2. 0. 2. 2. 1. 2. 1. 0. 0. 0. 2. 2. 0. 3. 1.
  2. 2. 4. 4. 3. 4. 0. 2.]] @ var0) <= 204.0
0.5 @ QuadForm(var0, [[2. 0. 2. ... 2. 0. 0.]
 [0. 2. 1. ... 1. 0. 1.]
 [2. 1. 2. ... 1. 0. 1.]
 ...
 [2. 1. 1. ... 2. 2. 0.]
 [0. 0. 0. ... 2. 0. 1.]
 [0. 1. 1. ... 0. 1. 0.]]) + trace([[1. 4. 0. 1. 0. 1. 0. 3. 4. 3. 4. 4. 0. 3. 2. 2. 3. 4. 1. 0. 2. 3. 4. 0.
  4. 4. 3. 3. 4. 1. 4. 4. 0. 2. 4. 4. 3. 4. 0. 4. 2. 3. 0. 0. 0. 3. 3. 3.
  3. 0. 3. 3. 0. 0. 4. 0. 3. 4. 2. 3. 3. 3. 2. 0. 4. 0. 1. 0. 3. 0. 1. 0.
  4. 4. 2. 0. 1. 2. 1. 4.]] @ var0) <= 236.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[2. 0. 2. ... 2. 0. 0.]
 [0. 2. 1. ... 1. 0. 1.]
 [2. 1. 2. ... 1. 0. 1.]
 ...
 [2. 1. 1. ... 2. 2. 0.]
 [0. 0. 0. ... 2. 0. 1.]
 [0. 1. 1. ... 0. 1. 0.]]) + trace([[1. 4. 0. 1. 0. 1. 0. 3. 4. 3. 4. 4. 0. 3. 2. 2. 3. 4. 1. 0. 2. 3. 4. 0.
  4. 4. 3. 3. 4. 1. 4. 4. 0. 2. 4. 4. 3. 4. 0. 4. 2. 3. 0. 0. 0. 3. 3. 3.
  3. 0. 3. 3. 0. 0. 4. 0. 3. 4. 2. 3. 3. 3. 2. 0. 4. 0. 1. 0. 3. 0. 1. 0.
  4. 4. 2. 0. 1. 2. 1. 4.]] @ var0) <= 236.0
0.5 @ QuadForm(var0, [[0. 1. 1. ... 1. 2. 2.]
 [1. 0. 0. ... 1. 1. 0.]
 [1. 0. 2. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [2. 1. 1. ... 0. 2. 1.]
 [2. 0. 1. ... 0. 1. 2.]]) + trace([[0. 0. 1. 0. 2. 2. 0. 0. 2. 3. 0. 4. 1. 2. 1. 2. 2. 1. 3. 4. 4. 1. 1. 4.
  4. 1. 2. 1. 4. 2. 4. 0. 3. 1. 2. 4. 0. 3. 3. 1. 1. 1. 1. 3. 2. 2. 3. 2.
  4. 1. 2. 0. 3. 1. 4. 3. 0. 4. 4. 2. 3. 4. 4. 2. 4. 4. 0. 4. 2. 3. 1. 3.
  1. 3. 1. 1. 0. 3. 4. 2.]] @ var0) <= 205.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[0. 1. 1. ... 1. 2. 2.]
 [1. 0. 0. ... 1. 1. 0.]
 [1. 0. 2. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [2. 1. 1. ... 0. 2. 1.]
 [2. 0. 1. ... 0. 1. 2.]]) + trace([[0. 0. 1. 0. 2. 2. 0. 0. 2. 3. 0. 4. 1. 2. 1. 2. 2. 1. 3. 4. 4. 1. 1. 4.
  4. 1. 2. 1. 4. 2. 4. 0. 3. 1. 2. 4. 0. 3. 3. 1. 1. 1. 1. 3. 2. 2. 3. 2.
  4. 1. 2. 0. 3. 1. 4. 3. 0. 4. 4. 2. 3. 4. 4. 2. 4. 4. 0. 4. 2. 3. 1. 3.
  1. 3. 1. 1. 0. 3. 4. 2.]] @ var0) <= 205.0
0.5 @ QuadForm(var0, [[2. 2. 0. ... 2. 1. 0.]
 [2. 0. 2. ... 0. 1. 0.]
 [0. 2. 2. ... 1. 2. 2.]
 ...
 [2. 0. 1. ... 0. 2. 1.]
 [1. 1. 2. ... 2. 0. 1.]
 [0. 0. 2. ... 1. 1. 2.]]) + trace([[1. 2. 4. 4. 1. 4. 0. 3. 3. 1. 2. 4. 2. 1. 4. 1. 4. 0. 3. 2. 4. 0. 3. 0.
  2. 4. 3. 3. 4. 0. 0. 0. 1. 3. 0. 0. 2. 2. 2. 3. 0. 2. 0. 4. 2. 0. 4. 3.
  0. 2. 0. 4. 0. 0. 0. 3. 1. 3. 3. 4. 4. 1. 3. 2. 3. 0. 1. 2. 3. 0. 0. 0.
  3. 4. 4. 4. 2. 1. 1. 2.]] @ var0) <= 226.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[2. 2. 0. ... 2. 1. 0.]
 [2. 0. 2. ... 0. 1. 0.]
 [0. 2. 2. ... 1. 2. 2.]
 ...
 [2. 0. 1. ... 0. 2. 1.]
 [1. 1. 2. ... 2. 0. 1.]
 [0. 0. 2. ... 1. 1. 2.]]) + trace([[1. 2. 4. 4. 1. 4. 0. 3. 3. 1. 2. 4. 2. 1. 4. 1. 4. 0. 3. 2. 4. 0. 3. 0.
  2. 4. 3. 3. 4. 0. 0. 0. 1. 3. 0. 0. 2. 2. 2. 3. 0. 2. 0. 4. 2. 0. 4. 3.
  0. 2. 0. 4. 0. 0. 0. 3. 1. 3. 3. 4. 4. 1. 3. 2. 3. 0. 1. 2. 3. 0. 0. 0.
  3. 4. 4. 4. 2. 1. 1. 2.]] @ var0) <= 226.0
0.5 @ QuadForm(var0, [[0. 1. 1. ... 0. 1. 2.]
 [1. 2. 0. ... 0. 1. 0.]
 [1. 0. 2. ... 1. 2. 1.]
 ...
 [0. 0. 1. ... 2. 1. 2.]
 [1. 1. 2. ... 1. 0. 0.]
 [2. 0. 1. ... 2. 0. 0.]]) + trace([[1. 4. 2. 3. 3. 1. 1. 4. 0. 2. 0. 4. 1. 3. 0. 3. 4. 0. 4. 1. 3. 4. 1. 2.
  3. 4. 3. 3. 4. 3. 1. 1. 1. 2. 0. 0. 3. 3. 3. 3. 1. 2. 2. 4. 4. 1. 1. 3.
  3. 3. 0. 3. 1. 3. 2. 2. 1. 0. 3. 2. 1. 0. 2. 0. 3. 0. 0. 0. 2. 4. 3. 0.
  4. 1. 0. 4. 1. 3. 0. 4.]] @ var0) <= 183.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[0. 1. 1. ... 0. 1. 2.]
 [1. 2. 0. ... 0. 1. 0.]
 [1. 0. 2. ... 1. 2. 1.]
 ...
 [0. 0. 1. ... 2. 1. 2.]
 [1. 1. 2. ... 1. 0. 0.]
 [2. 0. 1. ... 2. 0. 0.]]) + trace([[1. 4. 2. 3. 3. 1. 1. 4. 0. 2. 0. 4. 1. 3. 0. 3. 4. 0. 4. 1. 3. 4. 1. 2.
  3. 4. 3. 3. 4. 3. 1. 1. 1. 2. 0. 0. 3. 3. 3. 3. 1. 2. 2. 4. 4. 1. 1. 3.
  3. 3. 0. 3. 1. 3. 2. 2. 1. 0. 3. 2. 1. 0. 2. 0. 3. 0. 0. 0. 2. 4. 3. 0.
  4. 1. 0. 4. 1. 3. 0. 4.]] @ var0) <= 183.0
0.5 @ QuadForm(var0, [[0. 2. 2. ... 0. 2. 1.]
 [2. 0. 0. ... 1. 2. 0.]
 [2. 0. 0. ... 1. 0. 1.]
 ...
 [0. 1. 1. ... 2. 1. 1.]
 [2. 2. 0. ... 1. 2. 0.]
 [1. 0. 1. ... 1. 0. 2.]]) + trace([[3. 0. 4. 0. 4. 3. 3. 1. 2. 1. 4. 1. 0. 1. 4. 3. 4. 4. 3. 3. 2. 0. 2. 4.
  4. 3. 3. 2. 1. 2. 1. 2. 2. 2. 2. 2. 4. 4. 2. 1. 4. 2. 2. 0. 1. 0. 1. 3.
  1. 0. 2. 1. 4. 2. 4. 0. 4. 2. 0. 3. 1. 1. 2. 4. 4. 1. 0. 2. 4. 3. 2. 3.
  3. 0. 4. 4. 0. 4. 0. 4.]] @ var0) <= 191.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[0. 2. 2. ... 0. 2. 1.]
 [2. 0. 0. ... 1. 2. 0.]
 [2. 0. 0. ... 1. 0. 1.]
 ...
 [0. 1. 1. ... 2. 1. 1.]
 [2. 2. 0. ... 1. 2. 0.]
 [1. 0. 1. ... 1. 0. 2.]]) + trace([[3. 0. 4. 0. 4. 3. 3. 1. 2. 1. 4. 1. 0. 1. 4. 3. 4. 4. 3. 3. 2. 0. 2. 4.
  4. 3. 3. 2. 1. 2. 1. 2. 2. 2. 2. 2. 4. 4. 2. 1. 4. 2. 2. 0. 1. 0. 1. 3.
  1. 0. 2. 1. 4. 2. 4. 0. 4. 2. 0. 3. 1. 1. 2. 4. 4. 1. 0. 2. 4. 3. 2. 3.
  3. 0. 4. 4. 0. 4. 0. 4.]] @ var0) <= 191.0
0.5 @ QuadForm(var0, [[0. 2. 1. ... 1. 1. 1.]
 [2. 2. 1. ... 1. 2. 0.]
 [1. 1. 2. ... 0. 2. 1.]
 ...
 [1. 1. 0. ... 2. 1. 0.]
 [1. 2. 2. ... 1. 2. 0.]
 [1. 0. 1. ... 0. 0. 2.]]) + trace([[3. 0. 3. 3. 3. 1. 1. 3. 4. 2. 0. 0. 0. 4. 3. 0. 3. 0. 1. 1. 4. 0. 3. 4.
  3. 0. 2. 1. 4. 1. 2. 4. 0. 3. 4. 1. 1. 4. 4. 4. 4. 2. 2. 2. 2. 0. 1. 1.
  2. 2. 2. 4. 1. 4. 0. 0. 2. 4. 4. 0. 4. 3. 3. 2. 0. 1. 2. 0. 1. 3. 3. 0.
  4. 4. 0. 1. 4. 4. 3. 3.]] @ var0) <= 134.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[0. 2. 1. ... 1. 1. 1.]
 [2. 2. 1. ... 1. 2. 0.]
 [1. 1. 2. ... 0. 2. 1.]
 ...
 [1. 1. 0. ... 2. 1. 0.]
 [1. 2. 2. ... 1. 2. 0.]
 [1. 0. 1. ... 0. 0. 2.]]) + trace([[3. 0. 3. 3. 3. 1. 1. 3. 4. 2. 0. 0. 0. 4. 3. 0. 3. 0. 1. 1. 4. 0. 3. 4.
  3. 0. 2. 1. 4. 1. 2. 4. 0. 3. 4. 1. 1. 4. 4. 4. 4. 2. 2. 2. 2. 0. 1. 1.
  2. 2. 2. 4. 1. 4. 0. 0. 2. 4. 4. 0. 4. 3. 3. 2. 0. 1. 2. 0. 1. 3. 3. 0.
  4. 4. 0. 1. 4. 4. 3. 3.]] @ var0) <= 134.0
0.5 @ QuadForm(var0, [[0. 1. 1. ... 0. 1. 0.]
 [1. 2. 1. ... 2. 1. 2.]
 [1. 1. 2. ... 1. 0. 2.]
 ...
 [0. 2. 1. ... 2. 0. 1.]
 [1. 1. 0. ... 0. 0. 1.]
 [0. 2. 2. ... 1. 1. 2.]]) + trace([[4. 2. 0. 4. 4. 2. 3. 4. 1. 3. 4. 4. 4. 2. 0. 0. 4. 3. 2. 0. 1. 1. 1. 1.
  3. 2. 0. 3. 4. 3. 4. 1. 3. 0. 2. 0. 2. 3. 4. 1. 2. 1. 4. 0. 2. 4. 2. 0.
  3. 1. 3. 0. 4. 0. 1. 4. 1. 1. 4. 0. 3. 2. 0. 0. 2. 1. 1. 0. 1. 1. 3. 3.
  2. 1. 1. 1. 2. 2. 2. 1.]] @ var0) <= 169.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[0. 1. 1. ... 0. 1. 0.]
 [1. 2. 1. ... 2. 1. 2.]
 [1. 1. 2. ... 1. 0. 2.]
 ...
 [0. 2. 1. ... 2. 0. 1.]
 [1. 1. 0. ... 0. 0. 1.]
 [0. 2. 2. ... 1. 1. 2.]]) + trace([[4. 2. 0. 4. 4. 2. 3. 4. 1. 3. 4. 4. 4. 2. 0. 0. 4. 3. 2. 0. 1. 1. 1. 1.
  3. 2. 0. 3. 4. 3. 4. 1. 3. 0. 2. 0. 2. 3. 4. 1. 2. 1. 4. 0. 2. 4. 2. 0.
  3. 1. 3. 0. 4. 0. 1. 4. 1. 1. 4. 0. 3. 2. 0. 0. 2. 1. 1. 0. 1. 1. 3. 3.
  2. 1. 1. 1. 2. 2. 2. 1.]] @ var0) <= 169.0
0.5 @ QuadForm(var0, [[0. 1. 0. ... 0. 1. 1.]
 [1. 0. 1. ... 1. 2. 0.]
 [0. 1. 2. ... 1. 1. 1.]
 ...
 [0. 1. 1. ... 2. 2. 0.]
 [1. 2. 1. ... 2. 2. 1.]
 [1. 0. 1. ... 0. 1. 0.]]) + trace([[1. 4. 1. 3. 3. 3. 0. 2. 4. 2. 4. 3. 1. 0. 4. 0. 1. 3. 2. 2. 4. 2. 0. 0.
  1. 0. 0. 2. 2. 1. 2. 2. 0. 3. 1. 0. 3. 4. 2. 0. 2. 3. 1. 3. 1. 2. 3. 2.
  2. 2. 2. 4. 2. 0. 3. 4. 1. 0. 1. 1. 0. 0. 4. 2. 0. 0. 3. 0. 4. 3. 0. 4.
  3. 1. 0. 4. 4. 3. 1. 0.]] @ var0) <= 222.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[0. 1. 0. ... 0. 1. 1.]
 [1. 0. 1. ... 1. 2. 0.]
 [0. 1. 2. ... 1. 1. 1.]
 ...
 [0. 1. 1. ... 2. 2. 0.]
 [1. 2. 1. ... 2. 2. 1.]
 [1. 0. 1. ... 0. 1. 0.]]) + trace([[1. 4. 1. 3. 3. 3. 0. 2. 4. 2. 4. 3. 1. 0. 4. 0. 1. 3. 2. 2. 4. 2. 0. 0.
  1. 0. 0. 2. 2. 1. 2. 2. 0. 3. 1. 0. 3. 4. 2. 0. 2. 3. 1. 3. 1. 2. 3. 2.
  2. 2. 2. 4. 2. 0. 3. 4. 1. 0. 1. 1. 0. 0. 4. 2. 0. 0. 3. 0. 4. 3. 0. 4.
  3. 1. 0. 4. 4. 3. 1. 0.]] @ var0) <= 222.0
0.5 @ QuadForm(var0, [[2. 1. 1. ... 2. 2. 1.]
 [1. 2. 1. ... 1. 1. 1.]
 [1. 1. 0. ... 0. 1. 1.]
 ...
 [2. 1. 0. ... 2. 1. 1.]
 [2. 1. 1. ... 1. 0. 0.]
 [1. 1. 1. ... 1. 0. 2.]]) + trace([[1. 1. 0. 3. 3. 2. 3. 4. 4. 4. 1. 1. 2. 4. 2. 1. 2. 0. 3. 3. 2. 1. 3. 3.
  3. 0. 4. 0. 2. 0. 3. 1. 4. 0. 4. 0. 1. 4. 1. 2. 2. 1. 3. 3. 3. 0. 3. 3.
  1. 2. 3. 3. 4. 0. 4. 3. 2. 4. 0. 2. 0. 2. 4. 0. 4. 4. 4. 1. 0. 1. 3. 0.
  2. 1. 2. 0. 0. 2. 2. 4.]] @ var0) <= 178.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[2. 1. 1. ... 2. 2. 1.]
 [1. 2. 1. ... 1. 1. 1.]
 [1. 1. 0. ... 0. 1. 1.]
 ...
 [2. 1. 0. ... 2. 1. 1.]
 [2. 1. 1. ... 1. 0. 0.]
 [1. 1. 1. ... 1. 0. 2.]]) + trace([[1. 1. 0. 3. 3. 2. 3. 4. 4. 4. 1. 1. 2. 4. 2. 1. 2. 0. 3. 3. 2. 1. 3. 3.
  3. 0. 4. 0. 2. 0. 3. 1. 4. 0. 4. 0. 1. 4. 1. 2. 2. 1. 3. 3. 3. 0. 3. 3.
  1. 2. 3. 3. 4. 0. 4. 3. 2. 4. 0. 2. 0. 2. 4. 0. 4. 4. 4. 1. 0. 1. 3. 0.
  2. 1. 2. 0. 0. 2. 2. 4.]] @ var0) <= 178.0

Process finished with exit code 1
```

**Comment by QiyaoWei** [comment]
testing complete
